# Generated by Django 5.2.4 on 2025-08-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Product Name")),
                (
                    "barcode",
                    models.CharField(
                        help_text="Unique barcode for the product.",
                        max_length=100,
                        unique=True,
                        verbose_name="Barcode",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="Quantity"),
                ),
                (
                    "reorder_threshold",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="The quantity at which to trigger a low stock alert.",
                        verbose_name="Reorder Threshold",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("piece", "Piece"),
                            ("kg", "Kilogram"),
                            ("g", "Gram"),
                            ("l", "Liter"),
                            ("ml", "Milliliter"),
                        ],
                        default="piece",
                        max_length=10,
                        verbose_name="Unit",
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Expiration Date"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["name"],
            },
        ),
    ]
